[package]
name = "visualizer"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

[profile.release]
debug = 1

# # Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
simulator.workspace = true 
bevy.workspace = true 
bevy_egui.workspace = true
bevy_panorbit_camera.workspace = true 
bevy_infinite_grid.workspace = true
egui_extras.workspace = true
nalgebra.workspace = true
flight_controller.workspace = true
toml.workspace = true


[features]
default = []
noise = []
