[package]
name = "res_controller"
version = "0.1.0"
edition = "2024"

[dependencies]
res.workspace = true
ridge.workspace = true
nalgebra.workspace = true
db_common.workspace = true
serde.workspace = true
flight_controller.workspace = true
loggers.workspace = true
drone.workspace = true
