[package]
name = "quad-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
rand_xoshiro = "0.6.0"
rand = "0.8.5"

[features]
default = []
noise = []
