[package]
name = "simulator"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
# bevy.workspace = true
rand_xoshiro.workspace = true
rand.workspace = true
libm.workspace = true
fast-math.workspace = true
nalgebra.workspace = true
fastapprox.workspace = true
flight_controller.workspace = true
pyo3.workspace = true
pyo3-log.workspace = true

[features]
default = []
noise = []
temp = []
