[package]
name = "bf_controller"
version = "0.1.0"
edition = "2024"

[dependencies]
flight_controller.workspace = true
libc = "0.2.169"
once_cell = "1.20.2"
tempfile = "3.17.1"
uuid.workspace = true
log.workspace = true
