[package]
name = "environment"
version = "0.1.0"
edition = "2024"

[dependencies]
simulator.workspace = true
pyo3-log.workspace = true 
pyo3.workspace = true
nalgebra.workspace = true
flight_controller.workspace = true

